---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# - ./angelnu.yaml
  - ./backube.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./cloudnative-pg.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./kyverno.yaml
  - ./metrics-server.yaml
  - ./openebs.yaml
  - ./piraeus.yaml
  - ./postfinance.yaml
  - ./rook-ceph.yaml
  - ./stakater.yaml
# - ./xenitab.yaml
