apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:iL0RsmU6ASZSGztetDbxlkJrQkCvHS527xq+MypmfSBLrXRR,iv:7mk+WzXFIX2q8Hn8eJ7XavHyvdxS9q5JtBh82gUx6rI=,tag:X+CXHlXTFc9fYBvwygZqSQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:9xW3nTcAnkMVdinpdUNR21HX3F//W5y/phRJCZc9Rz/OkulpwRS7DYqtyf/tnPAEMYrmVys2k0v2rZGjf5QJ7a2VYLug6IpVdvBTh5z0mR+dUlRVcnYCCH8BEC8AgnF6LDRz4rxdE9qQWlcCsSy3Qr5lxrxoCRBI2OrZ9x/ACd+kjyWYmvMhe2QJdun2+B0yashnURV09nPJgtTM/9cM2i4eNVO25qZXxh5Lu9ef/A==,iv:5XoGLJhP/jzQShHMdRTF/QQliQLJUUpoACMXK8plz8g=,tag:472bbCRa7Bn6v8zaPqoRgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a72a4fs6rhtk7dxn5jf48y035gz3sj680ndmxt9jjwnh7ufq6ctqrgtnaw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMajVJaWxpY3M5dUlUcys1
            OGg1MUFUdFo0UzJIR08yT09scXE4MkVxMWlvCkFNN0c2aGtMZzNBbXBCNGFMWFJD
            enNRNmtKQVl4UzlOdUpyK1BwY3U3MUkKLS0tIGkrTjBydCtkZXV3aVRnd1Q1Tnpw
            bE13N1pKZ3d6YmlUYWVyRnBwUkJwdWMKuS+X5JxfSLHqBAl0/VocgMjxkqzwP9Z0
            rjuLMSth17b3n/CXR5LtNCjBWab0qjlWQPZzc2Oq4zyFyldTLlLxYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-09T05:08:24Z"
    mac: ENC[AES256_GCM,data:JesmLCwpTSU88FpVRF4KYuxFKApqZSqtsM4cjnMQeBpJZOHlnLvw3hyJau+OoSxbPjNfC6ediOkE6XG8q4e1bn2BjPhuZ3IdWsE1yTTbyTklA1UoLFc8kkQQOb99pxu0W0ACPSMixQWwI4nbwayMs3tUvuOvKQoqbzdz9Yb70XQ=,iv:TVu1dgcsKbE5Ac95DQjqU92V+Bu+f0+M9+cw7G6R9WQ=,tag:Vtd2CzTa2IWSlzDbWXUJ7g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
