apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:A3waR4vjN5ouX7okI8kwK8S0pdCEHC/Fe3sUUi62acv8GdTalSji5Q==,iv:/EuyNkZ7NDuZRonqw6m5AHStaJL0tPO3n4eNsr7FeKE=,tag:3iDMu62lt35OfeoNEvM1Mg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a72a4fs6rhtk7dxn5jf48y035gz3sj680ndmxt9jjwnh7ufq6ctqrgtnaw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4SWNvbWVha1k5cjBIb1Vm
            MFhSazEzeVBLbkpkd24vUkdWZkhFUXp3Umo4CjF5d2Y5VXlWdDBMZHM0VHRLK3cw
            TnhBNE1vVU05djRzUVlhbWRUWDhkb3cKLS0tIFdHaytTU3lyRlNpOE5SbnhQVlBO
            U1lzUVM4amhqS2NsdHpwRmxlUmoyNFkKiM4w8DFcFDk4ZUR3Yp6TFNrKU2r3+6Uq
            iGYRGnjPc60VHry3bYlkgetcelpcUXkqNTxfbmNKVgIrzXHKkwxjWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-09T06:00:59Z"
    mac: ENC[AES256_GCM,data:HTAPZGJ3ZzZ4VcTz+YFJxyLWe0vFgCHp791W7NZ2yOJLnfYxTNp4+Hsp9ETkb/b8T9LrJS0ZjM+e+4qB21O47KjxpUZmUuSNpKCwAe+hqquTnehfUMjUQHCxjC+L9Ip0vjsqZoWHj/rKII80qEry7iDXLTUr9adm8OFlO/yhnLs=,iv:x8TNx72Suf3zlh0ML1UEuauaIFaqEAzAXnTem5o8H30=,tag:zFqrwq+h1olseATDffrqmA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
