apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:jcz/A5l6VN2ZBAClYGb3Ujd/z9KitlfLKO3Ds/7/WBgbMsx40FY/1WrDkaX/R97DJdhvG34/f4ZcMeb+2UkTI3l8dnvbMk6p/FaASaXPKF8XsB52/E5tW2VKMWBK7Q==,iv:vLHL09p7oWn38jxhCnlHKleVACg8D0WXHA9yAit+NXQ=,tag:UEkAkyo2id7eS/sXHLGWeA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:jcJ1TeFub8JgdBk=,iv:2Zsw0qwjTkgXuZFO0Tb31qqHr2PWkufFYu1LSUrdDTQ=,tag:C+3+KR8yBuMTX0/bNbtYTg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:8R1Vbp3p4UwuL8EYDUWy0Q==,iv:aWFshjru1E7ifJFrtyOXuggvuNwtE8J5/kC3oPHOKcQ=,tag:EYl3wXmynXNZVYqpdGHMRQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:pfN7sqYDATex1RiMNGZjQy6zEP3oiNAtHWR63vJ9KZf6sC2l,iv:ZL0WXQNJX14pu5Fw34K+zVbolxqwXmVaiRWwtXmv3HY=,tag:nJjdGn+4mCa3dOdSaaF0aw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a72a4fs6rhtk7dxn5jf48y035gz3sj680ndmxt9jjwnh7ufq6ctqrgtnaw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZlBxeHEwMDYrMGowc0h5
            VHFFVXdvM3M4R2V5WG41SWhZekthRUNCaG44ClNuVDEwUEF3RWJtekFiSmZhMHdR
            Um9GNTJpQ2thOG5VZEFJdzBFS3Y1UDQKLS0tIE1ZQm5tcTBkQzk0NTJLbytuR0xO
            WkltZERNbjVkZjlzYVdscmROT3BacGsKvmxu8282M1KJxfAkZATZ5LMwkryA5gVm
            JMyZnZErpQsUGB+IsyiNgt+/qWQ1ekUcp6yg1rS1+6GMzzuzucbJXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-09T07:35:01Z"
    mac: ENC[AES256_GCM,data:b45aooXQUMb05JekeEcK0rBnVVv9UYOmbMIn4iRYD0WRwqUGsi2EzgtpjwRVR3PIKPbpYSR30UzznpykBwxxvnBcon3lFqyGgb0/B0l+bUs/V/rna2ZmBAgyvUSgPamZRHEJ1gzfzqPXuQiB6e5sXgFvlDoIQ7m/FrxBKH/tH8o=,iv:YFDTRTzhxGcgPbzi3nA9qyhF7PM19XmSRDVFhf++opg=,tag:hr+u54qcYFZqAofGuCgqGg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
