apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:qoM4FlAtLgQTnqLABhcrfCsmXcO8cgLJrZZkn8j/5FTXiYRFL0MGFJW3BC118Q1B1EeOtMUg4SAX1Hg/8h8oLn+00r2DiVgdCcpE/jtpzq0n5gtj2isfXV3ulpw3Lg==,iv:KFla9nwF9W8+GjNaqchhZAvGeyQnJAWUQ4KBKHrKitU=,tag:Ec+FV/htji8pQUJZzG8Yqg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:BTwi+ExTVQ1me+w=,iv:r9XGbkFT/PhTXB7ohBEK8DfYZaqRwT2as+5lnEoe41k=,tag:F0vTcms3+iR2TbJdqtK9mw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:VT1/MZyqoWg5ekyh7RZrOQ==,iv:9p8oibZK6UJIVWxZBuUhZtbGyyCLe48Q6ZJy8QKN4Lg=,tag:HzjvzbHnkVLRDMY3pqN9Rw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:deetDCYPbaKVB7066ZwY0cQT+l7+eF2dz2GVYW6d8/fQJ5kx,iv:u9WzGIIkdg9kh2PpFsZE0lomW8dVQOFEVzlKPsMp+/c=,tag:5Mip4eRGtsscuDJtfQIz1w==,type:str]
    SECRET_DOMAIN_CC: ENC[AES256_GCM,data:Xz8py3SLmbwziw==,iv:U132YyrC6hnBtO3gGOdO+ic+o3x1dHM+jE8c2MfWCa8=,tag:r6JFGikeWVz+YAnxc9UsaA==,type:str]
    SECRET_DOMAIN_CO: ENC[AES256_GCM,data:i10HOjVvJimMOQ==,iv:5lCE7Wx3RgCzY1wr/IDMEyYETvrUd/61FwBg/vZfPaI=,tag:kZH7PY87dwPL64oQinWy7Q==,type:str]
    SECRET_DOMAIN_TV: ENC[AES256_GCM,data:uffDEJ8EcWaq/A==,iv:f+Z2KnwD+BiUQW19+FKhdDdIudkQgtGdQqA+OIcg3Po=,tag:laoEDXYE/IL/fLB4gFfjrw==,type:str]
    AUTHELIA_SENDER: ENC[AES256_GCM,data:cGg6kvzaHnhHd9uNoPEZJoWQLL1apQ+Udxba,iv:d+XljlLm8iUL8zOrLGbL2SxXraeyy7U2iFZumrCew9E=,tag:vIAzFpZvafq2M5u/CWMcQA==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:XA+Ms6Mq5EkYtXU2CHzPCA==,iv:XDH/+ToKX0DHd7hxf8Q6yTbFAYveY2lMLr77lggxOlo=,tag:1KJjKLjdKpuUvHmtEiX8IA==,type:str]
    NFS_SERVER: ENC[AES256_GCM,data:sHl2qxyqj+SFbC8=,iv:S+I81SXgqvN1YBkw4tSYfcepqqoCUCUFbT0zy+pPKoY=,tag:x+mANI3eSR73F0r5VfrKbw==,type:str]
    NFS_DOWNLOAD: ENC[AES256_GCM,data:a8Derw3RolrlXU4QdVtiRKU=,iv:F23K9XjyEJNPtgazjGPprHjDx+re+Iq/bykn5LxeSYc=,tag:5Yp3oc/A4AXKZbpNCn04mQ==,type:str]
    NFS_MUSIC: ENC[AES256_GCM,data:Tyhk+NcYmsANmhB8unM=,iv:pNCMz60uJiknEIuP+p/UyxBFOs/J9W/v5Zz3RcqcFS4=,tag:nhD8VV3R4ywgJw/x5mkpTg==,type:str]
    NFS_MEDIA: ENC[AES256_GCM,data:84ZJi3EDRQzhLUkt8g4=,iv:2KmNdo1vd8t4wRkorQdbZQVU+M2C5zMUaAx0eNgNpXk=,tag:kxfQaROQJE0qiFraKnzelw==,type:str]
    NFS_BOOKS: ENC[AES256_GCM,data:Fm7Oy8j2/nj78J3hqL8=,iv:gzS1MpOd1OPIbS5j0qbLoMboSBfNxSpao8MO45CMbEw=,tag:NpeUBTFHA1QiQtqBHatl3w==,type:str]
    NFS_KUBERNETES: ENC[AES256_GCM,data:u8LR/sv/W+f6vsSAsBmwWtgKnQ==,iv:GMhVVskXpVx4Mupf94bs9h+fALJp9FSJpQ1TAV5rCO4=,tag:MO/v8oyZV2eOSrs3/yABig==,type:str]
    NFS_CSI_VOL: ENC[AES256_GCM,data:X1EC9swSzV5Fo67QohpoRBw5UA==,iv:/HR27HMN5niytvdd94mBdMb8OFTncYwubgabkm+YStw=,tag:wphDQ0n9FLIF143T8XtjXQ==,type:str]
    NFS_SUBDIR_VOL: ENC[AES256_GCM,data:L1PG16EqTtlzRDjt71WbfhbRAW7SBl0=,iv:6zS1YgpbIb/8F5H/hx8v7n4Tm/2VSBeNHn1SbkHyF4Y=,tag:ok61kmMfjHH2ORDxTAH3TA==,type:str]
    EMAIL: ENC[AES256_GCM,data:kv/vgw7T1Y50d7B9etMrww==,iv:BrWnPF+7R42s2NtsVzPn56tXtprsjwMFN32fpe8K9ew=,tag:6Bwx8TQl/3+d9C9G8X5QjA==,type:str]
    LONGHORN_BACKUP: ENC[AES256_GCM,data:QG4Uu/jQmKuCcAuyv/fXB4epoFt/SfXxtU3FfudOvSGllR8=,iv:bkw06+doKU8FRM6ytr+mdPTN1KSDh1NFbjBkSA/XPqk=,tag:zkLxd2nWwmS+T6ZOYKD5Kw==,type:str]
    NETWORK_K8S_CLUSTER_CIDR: ENC[AES256_GCM,data:AiYw/OIMQfwhh0Le,iv:yCUHqODUrA6JQExRShVPcSP41lo3vCUgI+v+FqjwXO0=,tag:nbSv4SYx9eX5G8ehJMTTPA==,type:str]
    NETWORK_K8S_SERVICE_CIDR: ENC[AES256_GCM,data:1anhkR7kQw0FClSD,iv:Dxzij+hkOlMVzBQQ3vDpbaIRnp+TzPscG4WP0zoYWLs=,tag:vDPwx7yMu9TQ7VPBxfNKJw==,type:str]
    SECRET_WIREGUARD_PORT: ENC[AES256_GCM,data:rsdMu14=,iv:8RBRnfqUHBj9kdiXKDR4XBPkOPSOgdZwNpMedyH5Hi0=,tag:l9BWVPXF5f+EP4Csu3092A==,type:str]
    NETWORK_SERVER_CIDR: ENC[AES256_GCM,data:TjzfS4ddIf93bQ==,iv:H2AJENniDd0z4pCy/24HhiGGudXJqJ8tYyOp7aCMUbY=,tag:8LxcUNDdjb2hwpV44BG9mw==,type:str]
    WORKSTATION_CIDR: ENC[AES256_GCM,data:d4MaCLPtLzmbSmCCrag=,iv:gQLjZRS6Cf+hCwBom3YGtE4F+0eA+51KONzJNh6U+BQ=,tag:G59W/dzKu6EMwmfOKDePWQ==,type:str]
    SECRET_PASSWORD: ENC[AES256_GCM,data:lq/4IArZgxQ=,iv:N+ziQN0JhV2Dn4dYbO2DcRCIiolzEVDMj3+1m3MnCs0=,tag:lq/hSw2AtUM0Qwx84s6KjQ==,type:str]
    SECRET_QB_USERNAME: ENC[AES256_GCM,data:EdSxud4=,iv:RdxLx7bwzKKyphBwnzDEem9Xr6Wko9qNLPwCIXmVzOo=,tag:h/tL/GYDG08WSsZw6Z4aGQ==,type:str]
    SECRET_QB_PASSWORD: ENC[AES256_GCM,data:/P7OLN9hOZI=,iv:+DQySutmfGZNtvlwSq5SaKnU4YuAL6AfUdrLWUDfYHk=,tag:9mOV8apKAtg1IFTVwlXMvw==,type:str]
    NFS_MINIO: ENC[AES256_GCM,data:NYw9envCkGyJBjDjZzg=,iv:LFHnQ8e0jfiS4VOMXoiRhEVH5HiG658r2HkO6VaB0Rg=,tag:8ZH7BiHcJUD48spNRfK37A==,type:str]
    SECRET_MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:/uiON3G/lqA=,iv:Q0n/fmc2JdL3idKEJXwe8ZjThueoK9TCoMyItSXjYGw=,tag:tkPn9qF79oGRuLLL7wOUTA==,type:str]
    SECRET_POSTGRESQL_ROOT_PASSWORD: ENC[AES256_GCM,data:10/IFhybOFs=,iv:lP5dGN08DYzhmhxhVpMtLUxGM76Zuo4GtXr7XAT2tgU=,tag:Wp3NylRiC+NvV28qtT0jog==,type:str]
    SECRET_KOPIA_PASSWORD: ENC[AES256_GCM,data:7Nqs+sOKfLg=,iv:cYOWVmalHxLijXtrM6BsCMJVLnHKFd8eee0mxj9AriM=,tag:Wvk6CQOmDA9SVqbor1pIJg==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:LJAOpZWJ0BRQdmw4x8/mZMCJBk8Zs6KJHbY=,iv:M/+1/f1PBTqg6dphd3hRD8F2I9yeUCwnoSCk6atpkP0=,tag:5cEzcXxs3TPRGY+9a6WCqQ==,type:str]
    TZ: ENC[AES256_GCM,data:w59FurV76mce6yvzyxMf7mdEXck=,iv:KLi+Tp+P+xyY14mZhNbNEH87xcJ0pflLWGLO2/eUDAY=,tag:ygQiJv1iZNwSotIbup+1ew==,type:str]
    SECRET_CLOUDFLARE_TUNNEL: ENC[AES256_GCM,data:wqR+KW6/HJw4qb+1HIWTQFxGCZ5SDmK5e8KImbWRi6AIV/4UYWsgKOhm6vqHi/dREBq236w=,iv:ON+J0w8yq0WNMGBKb/G4H04K9i5qV7OaxU/Y8SXzZew=,tag:fB2nfKHT+UrYDaGz199RnQ==,type:str]
    HARDWARE_DOMAIN: ENC[AES256_GCM,data:dMzTxuGv9EDwUg==,iv:nzSA9pxaAMG1/DNjyigAMpgqokNHIIEBA0v4CuLTw8k=,tag:osnmH4uiezIAZOEXShpRAw==,type:str]
    CLUSTER_NAME: ENC[AES256_GCM,data:pck1T/tiLA==,iv:5gbQd9sACoS+G6lPViPY4VPa2cUDqaalEMDguqg0te4=,tag:fk7PeZBce/2rAQLu61nbDA==,type:str]
    VNC_USER: ENC[AES256_GCM,data:2tAs2kE=,iv:QjVemxoLMNasZzoFztIWrzu7lJNsE3M4sJATyiMLKBA=,tag:f5BIUWCuqNp6a9IIQcaTcw==,type:str]
    VNC_PASSWORD: ENC[AES256_GCM,data:NxVEYpLc2Nw=,iv:rtmtv6f68Mu5O6JgzjjokQ0h9xqgHLYX+8jTNsKdLO4=,tag:LReZSq8kgflmborDQB7Veg==,type:str]
    SECRET_BOOKSTACK_DATABASE_PASSWORD: ENC[AES256_GCM,data:/4rHn0aJdD8=,iv:tKlEuTPh1aj41DTmP/ug3EpFb/tnz1Z58vXV6F3dPbg=,tag:B7EopLnbj5JPFCDoLoAhKw==,type:str]
    SECRET_RANCHER_ADMIN_PASSWORD: ENC[AES256_GCM,data:mNv1dBdTQUw=,iv:s0tG99Juiv2G4gVfZBhzbVvUl/NrumnB8C0bpFPA6i0=,tag:INJhYy7qM9t0S45BaMxuCg==,type:str]
    INFLUXDB_ADMIN_USER: ENC[AES256_GCM,data:mDrqVf4=,iv:HhPBRPyrFG25Q/ealLoMQptcm1nMI+y/uFQ2dPfTTtM=,tag:SIto01n/3Mm/xcXYObkfdQ==,type:str]
    INFLUXDB_ADMIN_USER_PASSWORD: ENC[AES256_GCM,data:nYo1uRb9UtQ=,iv:CDeJVbucrv2ON3i1rYba6PLME0M7e4F8eh3KlrnQN6g=,tag:FeDDwzllkBfv9NnKngBqwQ==,type:str]
    INFLUXDB_ADMIN_USER_TOKEN: ENC[AES256_GCM,data:VL1MDtHsf2A6Qg==,iv:E9OICTAoGfC/3WjHmGyY1zpOVBV5bgUjC+iIECD8bOI=,tag:dlVmTbiWcXy33lOsQGLKwQ==,type:str]
    PGADMIN_EMAIL: ENC[AES256_GCM,data:xlkzndetGK6DqAV0QXoGFw==,iv:zQAXqeIYO3w2k5AOVehSJKXGWF6mYRcxJ3MR1NaxKM8=,tag:XVV5FBrCbe7EDHggC03iDw==,type:str]
    PGADMIN_PASSWORD: ENC[AES256_GCM,data:dlMVphK8BYM=,iv:FTJz5sXYPlS+1P7R/+swLAwnZgh6Sg9OTtvc/iWLwRY=,tag:LQm3zLcFKMvFk1YdQ/W3hA==,type:str]
    AUTHELIA_SMTP_PASS: ENC[AES256_GCM,data:WghK53AyOgFc5uzvwY1vzA==,iv:AsYBfiQl/xDysLCn+cJaw4/h2c7K9zgPmxniTKxUThg=,tag:nGcD+L/QdLpa8MwX9XLT/g==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:tSHKIoVNJjRiBF8=,iv:a2U/aJczrwifsCdTUgG9uzO729MiszLbX9xm15GPejk=,tag:ZRDwHFzZKnVTu+CbBYKPNg==,type:str]
    SECRET_OUTLINE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:9YK1tTQipRThET/pWgGt+duZA+kS+khLtcc=,iv:5eHM1ECx21fBaH8jpobYLgKEu/+8VvK7v56FIIq7v5s=,tag:QAU6SevDHQDX+d8zNWdnOA==,type:str]
    OUTLINE_POSTGRES_PASS: ENC[AES256_GCM,data:19WUtynnrJRvB8yktNNSpPaquEPndDJSS80=,iv:uGsTJi+bSQMvl0SHUOFDPftyffXhkpnvtLZJMvs1lG8=,tag:TZyc9EH6IDyMNj2MIa9B0Q==,type:str]
    OUTLINE_POSTGRES_USER: ENC[AES256_GCM,data:vs4nOG2AUA==,iv:LPAdFqNzfmAULKOfLU63W39REdHnfNuetYD+sgmgO8M=,tag:Koy1YNxlrX45+/lSxGTPZQ==,type:str]
    SECRET_GITEA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:IKb8aEE4+LJdHphzIhkazfCcw58JmUwX7q0=,iv:tfOkkfP7NV6g+UgaXRlLbZHSrDSgt8lZR+62VILzs7o=,tag:CKdsql8z+kiGkUePhFiLtg==,type:str]
    SABNZBD_API: ENC[AES256_GCM,data:V3uSSuuNlvjWMhGOJGBEfINy7T0Pa8y3uF3Qu7LsGdo=,iv:1apFxqI/GzzSkXyYUlUdLmk2tQyNaTV3d8P3A1hCb2w=,tag:AfWGWBOJU04LZ9WHCG0EPA==,type:str]
    SYNO_ADMIN: ENC[AES256_GCM,data:cBnf9ybnFro=,iv:m5TBXwy/xg7A3gQ9Nv0Bb6UYjGb+aPxd64JetcTAxIs=,tag:JRfVZ+33qYCTUAqUdMgyqw==,type:str]
    SYNO_PASSWORD: ENC[AES256_GCM,data:Kh4YV7xt558=,iv:2RleZscbHryzMaH7faiaVUcwWD90dBIl99K4N4Uo/uc=,tag:+Bpw5Knb1FFARsyDGiho+A==,type:str]
    NAS_SERVER: ENC[AES256_GCM,data:SYFs7ColQ3yb81w=,iv:m7qC9IhygWrc0viUBAaMM+/E16SosqIgB9dYXTnBOkY=,tag:zi+ilwnFsTYedjeOHjPOLA==,type:str]
    QNAP: ENC[AES256_GCM,data:ys6SyUUrhKsqun8=,iv:Ccl8Tl93mF1awsStTms+3Q9keTBBhlTfJttuIgsuZ0A=,tag:fvJf1WfxHTfVq0MiSe02ZQ==,type:str]
    CUSTOM_WEB_PORT: ENC[AES256_GCM,data:5zc9iA==,iv:+pdRG4i0+0KnuE2QRE+7MFXeFEm2I98XhcfsWIcBlwU=,tag:57lIDOyuG7XskWECMkJXHg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a72a4fs6rhtk7dxn5jf48y035gz3sj680ndmxt9jjwnh7ufq6ctqrgtnaw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRzEvekVkeEtMOUtvTU5Z
            VzVXU2sydlJwVURPM2g2UWVGOTFFY3JGVXdVCjEvYW5veTVnR0dNNGZQVzEySGJn
            UW1WRFdmZ0pwZklPTlFLWWpkVkdiS0EKLS0tIHF2WCtPZ3ZHdDdrektXSVdpc01W
            Y04zK0QvMzZKTlcwZEFhT2w1MFo5a00KLmLStPVq7aQoKUSsuCic9KQOnd/rTJYK
            Ke+1Ag4U8bbpglPTLhNKcPIPvwx0OqqWm2Oct+KSP74f4wqgNIKWRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-29T04:18:13Z"
    mac: ENC[AES256_GCM,data:YT3x8880aiiYN6Uzp2lyf3sOJMjHlnqxEzVl8ghAhY4HOWXHSLC/EE/oSmhWUHc5/AH9+4CbZFQLSZSYhlY1NyhwGU0VdHIaREXfVn76n7bOEjlZ2a6tL1C/qNL5OZV6vPy2odmxyjitW5+1IYTLx9H+nMRpMpS4/e4ZsqjhNE4=,iv:K0vcqZd9OHuhV731X4/5ExMMHjxSEVCyxDKYf7I+E6g=,tag:uXIicggA0ppaOrWlD39JoA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
