apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:JhaQP8tj2ghJMbxGI7Z9kD5RSINa0Sta5L6iSxLfy8o=,iv:4wPswaUKnYR27YVGBt87pxe7/eAGnLSMMOnP9b+UOr0=,tag:WXjoYMgeBPiD9kAR5Lqo/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a72a4fs6rhtk7dxn5jf48y035gz3sj680ndmxt9jjwnh7ufq6ctqrgtnaw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbVp1N01vL2FjTkhuazBk
            aGNucUZUYUEwMW5CZHpVN0R2Z1NJbG5makRnClI4RHhKaHUzb1RQOVVnTDc3WWJE
            NWthVUtrYlRBWEtEMmpFcE41aGpDL1UKLS0tIEpDelVKR3BFVWJoWSswSjFMZzgy
            eHh0M1NhT2FaWEdCaFQzdmdvdm9FTmcK4f2vysXKp++uTFw3A0qdN3fSQ/0u76qB
            f5xzJRz9gg7XzLSGl2gcLrVoQCVSKkR81KsS7D++CYwnsay5Qd/eNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-09T07:35:01Z"
    mac: ENC[AES256_GCM,data:4pf4tBm06XTLbwS2UKCTUh0Ww0H8+8UhkkuVi8FqR0CqBkzIQ52aaYTBYJ96w0cgJX3hArItNxh/WWOv42JPayInkwCvPYeXVnD6MndhIzAZZO5PRvId3xHFpgT/lugp3w4XpNyEdBqrkaVK4QhDjR3w+0OINSIQ9OAeGqtM9DE=,iv:iTIYbXrlFXPSFr6AC8f/0y4xg+eU1Mb/SwXEHjbScmI=,tag:JBwZAB7NHKFfOqzWWci9Ag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
